import streamlit as st
from utils.state import init_state, new_trace_id, log_event
from utils.components import app_header

st.set_page_config(page_title="Report generator", page_icon="📝", layout="wide")
init_state()
app_header("Report generator", "Format and download ranking report")

st.markdown("### Compose")
title = st.text_input("Report title", "AI Model Ranking — Latest Batch")
intro = st.text_area("Introduction", "This report summarizes model performance on selected Reddit AI discussions.")
body = st.text_area("Body (auto from ranking)", st.session_state.get("last_report_txt", "No ranking prepared yet."))
footer = st.text_area("Footer", "Generated by Ranking Agent console.")

fmt = st.selectbox("Format", ["txt", "md"])
if st.button("Generate file"):
    trace_id = new_trace_id("report")
    content = f"# {title}\n\n{intro}\n\n{body}\n\n{footer}" if fmt == "md" else f"{title}\n\n{intro}\n\n{body}\n\n{footer}"
    st.session_state["reports"].append({"trace_id": trace_id, "title": title, "fmt": fmt, "content": content})
    log_event("report.generated", data={"fmt": fmt, "size": len(content)}, trace_id=trace_id)
    st.success(f"Report generated. trace_id={trace_id}")
    st.download_button("Download", data=content, file_name=f"report.{fmt}", mime="text/plain")